---
apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-http
  namespace: demo
spec:
  type: NodePort
  ports:
    - port: 3080
      targetPort: 80
      nodePort: 31000
  selector:
    app: http
